/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutJohnRouteImport } from './routes/about-john'
import { Route as BookSnookerCoachingRouteImport } from './routes/book-snooker-coaching'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SnookerCoachingRouteImport } from './routes/snooker-coaching'
import { Route as SnookerInsightsRouteImport } from './routes/snooker-insights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutJohnRoute = AboutJohnRouteImport.update({
  id: '/about-john',
  path: '/about-john',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSnookerCoachingRoute = BookSnookerCoachingRouteImport.update({
  id: '/book-snooker-coaching',
  path: '/book-snooker-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SnookerCoachingRoute = SnookerCoachingRouteImport.update({
  id: '/snooker-coaching',
  path: '/snooker-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const SnookerInsightsRoute = SnookerInsightsRouteImport.update({
  id: '/snooker-insights',
  path: '/snooker-insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-john': typeof AboutJohnRoute
  '/book-snooker-coaching': typeof BookSnookerCoachingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snooker-coaching': typeof SnookerCoachingRoute
  '/snooker-insights': typeof SnookerInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-john': typeof AboutJohnRoute
  '/book-snooker-coaching': typeof BookSnookerCoachingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snooker-coaching': typeof SnookerCoachingRoute
  '/snooker-insights': typeof SnookerInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-john': typeof AboutJohnRoute
  '/book-snooker-coaching': typeof BookSnookerCoachingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snooker-coaching': typeof SnookerCoachingRoute
  '/snooker-insights': typeof SnookerInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-john'
    | '/book-snooker-coaching'
    | '/sitemap.xml'
    | '/snooker-coaching'
    | '/snooker-insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-john'
    | '/book-snooker-coaching'
    | '/sitemap.xml'
    | '/snooker-coaching'
    | '/snooker-insights'
  id:
    | '__root__'
    | '/'
    | '/about-john'
    | '/book-snooker-coaching'
    | '/sitemap.xml'
    | '/snooker-coaching'
    | '/snooker-insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutJohnRoute: typeof AboutJohnRoute
  BookSnookerCoachingRoute: typeof BookSnookerCoachingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SnookerCoachingRoute: typeof SnookerCoachingRoute
  SnookerInsightsRoute: typeof SnookerInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-john': {
      id: '/about-john'
      path: '/about-john'
      fullPath: '/about-john'
      preLoaderRoute: typeof AboutJohnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-snooker-coaching': {
      id: '/book-snooker-coaching'
      path: '/book-snooker-coaching'
      fullPath: '/book-snooker-coaching'
      preLoaderRoute: typeof BookSnookerCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snooker-coaching': {
      id: '/snooker-coaching'
      path: '/snooker-coaching'
      fullPath: '/snooker-coaching'
      preLoaderRoute: typeof SnookerCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snooker-insights': {
      id: '/snooker-insights'
      path: '/snooker-insights'
      fullPath: '/snooker-insights'
      preLoaderRoute: typeof SnookerInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutJohnRoute: AboutJohnRoute,
  BookSnookerCoachingRoute: BookSnookerCoachingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SnookerCoachingRoute: SnookerCoachingRoute,
  SnookerInsightsRoute: SnookerInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
